### ISSUE TITLE
Using build in SD Card in Sparkfun Thing Plus RP2040 board

### ISSUE THREAD

**Issue by spectruma** [khoih-prog/RP2040_SD#1]
I am not quit sure if this is an issue or my lag of knowledge but it seems that the lib is not using the correct pin assignments when using below #defines...

For the board Thing Plus RP2040 the following pins (GPIOs) are used for the SPI communication.

```
MOSI  15
MISO  12
SCK    14
SS      9
```

With an oscilloscope I can see that SS is brought low but the other lines are not doing anything.
Hence, initialisation fails.
I am using this code for initialisation , which is derived from one of your examples

```
/*
  SD card connection

  This example shows how to read and write data to and from an SD card file
  The circuit:
   SD card attached to SPI bus as follows:
   // Arduino-pico core
   ** MISO - pin 16
   ** MOSI - pin 19
   ** CS   - pin 17
   ** SCK  - pin 18

   // Arduino-mbed core
   ** MISO - pin 4
   ** MOSI - pin 3
   ** CS   - pin 5
   ** SCK  - pin 2
*/


#if !defined(ARDUINO_ARCH_RP2040)
  #error For RP2040 only
#endif

#if defined(ARDUINO_ARCH_MBED)
  
  #define PIN_SD_MOSI       15              <-------- My assignments
  #define PIN_SD_MISO       12
  #define PIN_SD_SCK        14
  #define PIN_SD_SS         9

#else

  #define PIN_SD_MOSI       PIN_SPI0_MOSI
  #define PIN_SD_MISO       PIN_SPI0_MISO
  #define PIN_SD_SCK        PIN_SPI0_SCK
  #define PIN_SD_SS         PIN_SPI0_SS
  
#endif

#define _RP2040_SD_LOGLEVEL_       4

#include <SPI.h>
#include <RP2040_SD.h>

File myFile;

bool initSDCard()
{

    #if defined(ARDUINO_ARCH_MBED)
  Serial.print("Starting SD Card ReadWrite on MBED ");
#else
  Serial.print("Starting SD Card ReadWrite on ");
#endif
  
  Serial.println(BOARD_NAME);
  
  Serial.print("Initializing SD card with SS = ");  Serial.println(PIN_SD_SS);
  Serial.print("SCK = ");   Serial.println(PIN_SD_SCK);
  Serial.print("MOSI = ");  Serial.println(PIN_SD_MOSI);
  Serial.print("MISO = ");  Serial.println(PIN_SD_MISO);
  
// FAILS HERE
  if (!SD.begin(100000, PIN_SD_SS)) 
  {
    Serial.println("Initialization failed!");
    return false;
  }
  return true;
}
```
 
It seems using above #defines will not change actual drive lines used by the SPI lib ?

I made an experiment with Micropython on the same board and everything works like a charm.
So, no issue with the used µSD card whatsoever.  

```
RP2040_SD lib version 1.0.0
PlatformIO version: 5.1.1
platform=raspberrypi 1.2.0
based on Arduino-mbed RP2040 v2.3.1
Sparkfun Thing Plus RP2040
OS: Windows 10 /macOS
```

**Comment by khoih-prog** [comment]
You have to modify in the variant file, according to Sparkfun's [**RP2040 Thing Plus Hookup Guide**](https://learn.sparkfun.com/tutorials/rp2040-thing-plus-hookup-guide/software-overview).

Then keep the example code as is 

```
#if defined(ARDUINO_ARCH_MBED)
  
  #define PIN_SD_MOSI       PIN_SPI_MOSI
  #define PIN_SD_MISO       PIN_SPI_MISO
  #define PIN_SD_SCK        PIN_SPI_SCK
  #define PIN_SD_SS         PIN_SPI_SS

...
```

---
---

Note: Users trying to access the SD card slot will need to modify the pins_arduino.h file to reconfigure the SPI bus pins. However, this will make the SPI bus inaccessible through the breakout pins (when utilizing the SPI library).

On a Windows 10 computer, with the Arduino IDE installed through the App store, the location of the `pins_arduino.h` file is (in Windows):

`C:\Users\<username>\Documents\ArduinoData\packages\arduino\hardware\mbed_rp2040\<package_version>\variants\RASPBERRY_PI_PICO`

![image](https://user-images.githubusercontent.com/57012152/131226676-7f4c0d45-8324-478c-87da-7a036fdb1171.png)


Arduino folder for file modification
pins_arduino.h file in the RASPBERRY_PI_PICO folder. (Click to enlarge)
Users will need to modify lines 45 - 47 of the pins_arduino.h file to the following:

> // SPI
> #define PIN_SPI_MISO  (12u) //(4u)
> #define PIN_SPI_MOSI  (15u) //(3u)
> #define PIN_SPI_SCK   (14u) //(2u)


![image](https://user-images.githubusercontent.com/57012152/131226706-46eaaad5-eacc-4330-b77c-f75f9c7ceeed.png)

Line modifications to the pins_arduino.h file.

**Comment by spectruma** [comment]
thank you very much for the pointer. Now everything works. 
I'd wish not to had to modify pins_arduino.h, but if this is the only way (at least right now)
how cares ;-)

**Comment by khoih-prog** [comment]
Glad to know it's working for you now.

It's better that Sparkfun (or any company making RP2040-based boards) either 

1. adds support to those RP2040 cores by providing a set of variant files / directory or 
2. provides the fully compatible design to the core.

Hopefully this will be solved soon by the company's PR to add the board support (variants) to the cores.
