### ISSUE TITLE
Missing open file append

### ISSUE THREAD

**Issue by PitHerm** [khoih-prog/RP2040_SD#4]
I don't know if this is the right way to
but as far as i read the lib supports open file for read and open file for write
is open file for append not implemented ?

Pit

**Comment by khoih-prog** [comment]
It's already included in `FILE_WRITE`

```
#define FILE_WRITE (O_READ | O_READ | O_CREAT | O_APPEND)
```

You can compare to other file-system style

- `O_READ` == `r`
- `O_WRITE` == `w+`
- `O_WRITE | O_APPEND` == `a`
- `O_READ | O_WRITE` == `w+`
- `O_READ | O_WRITE | O_APPEND` == `a+`

Have a more detailed look at [**SD.h**#L161-L178](https://github.com/earlephilhower/arduino-pico/blob/master/libraries/SD/src/SD.h#L161-L178)
